import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { CalendarDays, FileText, Pencil, Sparkles, UserRound } from "lucide-react";
import Sidebar from "@/components/Sidebar";
import { getCurrentUser } from "@/lib/auth";

function normalizeAnswers(value: unknown): Record<string, unknown> {
  if (!value) return {};

  if (value instanceof Map) {
    return Object.fromEntries(value.entries());
  }

  if (typeof value === "object") {
    return JSON.parse(JSON.stringify(value));
  }

  return {};
}

function formatAnswer(value: unknown) {
  if (Array.isArray(value)) return value.join(", ");
  if (value === null || value === undefined || value === "") return "Not answered";
  return String(value);
}

export default async function ProfilePage() {
  const user = await getCurrentUser();

  if (!user) {
    redirect("/login");
  }

  const answers = normalizeAnswers(user.onboardingAnswers);
  const answerEntries = Object.entries(answers).filter(([, value]) => {
    if (Array.isArray(value)) return value.length > 0;
    return value !== undefined && value !== null && String(value).trim() !== "";
  });
  const joinedDate = user.createdAt
    ? new Date(user.createdAt).toLocaleDateString("en", { month: "long", year: "numeric" })
    : "Recently";

  const sidebarUser = {
    name: user.name,
    username: user.username,
    avatarUrl: user.avatarUrl,
  };

  return (
    <div className="flex min-h-screen bg-ink-950">
      <Sidebar user={sidebarUser} />

      <main className="relative min-w-0 flex-1 overflow-hidden">
        <div className="absolute inset-x-0 top-0 h-80">
          <Image
            src="https://picsum.photos/seed/foundershook-profile/1800/520"
            alt=""
            fill
            priority
            className="object-cover opacity-30"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-ink-950/30 via-ink-950/85 to-ink-950" />
        </div>

        <section className="relative z-10 mx-auto max-w-6xl px-6 pb-28 pt-10 lg:px-10">
          <div className="flex flex-col gap-6 border-b border-white/10 pb-8 md:flex-row md:items-end md:justify-between">
            <div className="flex flex-col gap-5 sm:flex-row sm:items-end">
              <Image
                src={user.avatarUrl || "https://picsum.photos/seed/user/160/160"}
                alt={user.name}
                width={128}
                height={128}
                className="h-32 w-32 rounded-2xl border border-white/15 object-cover shadow-card"
              />

              <div>
                <p className="mb-2 inline-flex items-center gap-2 rounded-full border border-gold-400/25 bg-gold-400/10 px-3 py-1 text-xs font-semibold text-gold-200">
                  <UserRound size={14} />
                  Founder profile
                </p>
                <h1 className="font-display text-4xl font-semibold text-white">{user.name}</h1>
                <p className="mt-1 text-sm text-mist-400">@{user.username}</p>
                <p className="mt-3 flex items-center gap-2 text-sm text-mist-400">
                  <CalendarDays size={15} />
                  Joined {joinedDate}
                </p>
              </div>
            </div>

            <Link href="/onboarding" className="btn-outline w-fit">
              <Pencil size={16} />
              Rebuild Bio
            </Link>
          </div>

          <div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">
            <section className="rounded-2xl border border-white/10 bg-ink-900/75 p-6 shadow-card backdrop-blur">
              <div className="mb-5 flex items-center gap-3">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gold-400/10 text-gold-300">
                  <Sparkles size={19} />
                </span>
                <div>
                  <h2 className="font-display text-xl font-semibold text-white">Bio</h2>
                  <p className="text-sm text-mist-500">Generated by the AI Bio Creator</p>
                </div>
              </div>

              {user.bio ? (
                <p className="whitespace-pre-wrap text-base leading-8 text-mist-100">{user.bio}</p>
              ) : (
                <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.03] p-6">
                  <p className="text-mist-300">
                    Your generated bio will appear here after onboarding.
                  </p>
                  <Link href="/onboarding" className="btn-gold mt-5">
                    <Sparkles size={16} />
                    Create Bio
                  </Link>
                </div>
              )}
            </section>

            <aside className="space-y-6">
              <section className="rounded-2xl border border-white/10 bg-ink-900/75 p-6 shadow-card backdrop-blur">
                <div className="mb-4 flex items-center gap-3">
                  <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/5 text-mist-300">
                    <FileText size={18} />
                  </span>
                  <div>
                    <h2 className="font-display text-lg font-semibold text-white">Profile Details</h2>
                    <p className="text-sm text-mist-500">From onboarding</p>
                  </div>
                </div>

                {answerEntries.length > 0 ? (
                  <dl className="space-y-4">
                    {answerEntries.slice(0, 6).map(([question, answer]) => (
                      <div key={question}>
                        <dt className="text-xs font-semibold uppercase tracking-[0.14em] text-mist-500">
                          {question}
                        </dt>
                        <dd className="mt-1 text-sm leading-6 text-mist-200">
                          {formatAnswer(answer)}
                        </dd>
                      </div>
                    ))}
                  </dl>
                ) : (
                  <p className="text-sm leading-6 text-mist-400">
                    Finish onboarding to fill out this profile framework.
                  </p>
                )}
              </section>
            </aside>
          </div>
        </section>
      </main>
    </div>
  );
}
